version: '3.9'
services:
  react:
    build:
      context: ./app-react
      dockerfile: Dockerfile
    restart: always
    container_name: react-app
    networks:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./app-react:/app
  db:
    image: postgres
    restart: always
    container_name: db-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_postegres
    volumes:
      - "/dbPostegres/data:/var/lib/postgresql/data"
    networks:
      - backend
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend
    container_name: adminer
  myapp:
    image: docker.io/bitnami/laravel:10
    restart: always
    ports:
      - "8000:8000"
    environment:
     - DB_CONNECTION=pgsql
     - DB_HOST=db
     - DB_PORT=5432
     - DB_DATABASE=dbPostegres
     - DB_USERNAME=postgres
     - DB_PASSWORD=postgres
    container_name: laravel-app
    volumes:
      - ./app-laravel:/app
    networks:
      - backend
    depends_on:
      - db
networks:
  backend:
    driver: bridge
