version: '3.9'
services:
  react:
    build:
      context: ./app-react
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "5173:5173"
    volumes:
      - ./app-react:/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123senha
  phpadmin:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  myapp:
    image: docker.io/bitnami/laravel:10
    ports:
      - "8000:8000"
    environment:
      - DB_DATABASE=db_teste
      - DB_CONNECTION=postgres
      - DB_HOST=localhost
      - DB_PORT=5432
    volumes:
      - ./app-laravel:/app
    depends_on:
      - db
